---
platform: linux

image: docker:///bosh/init

inputs:
  - name: bosh-vsphere-stemcell-version
- name: bosh-agent-zip
- name: bosh-agent-deps-zip
- name: bosh-agent
  path: gopath/src/github.com/cloudfoundry/bosh-agent
- name: ovftool-linux

  outputs:
    - name: vagrant_home
- name: bosh-vsphere-stemcell

  run:
    path: gopath/src/github.com/cloudfoundry/bosh-agent/ci/tasks/create-vsphere-stemcell-windows.sh

  params:
    RESOURCE_POOL_NAME: replace-me
  TEMPLATE_NAME: replace-me
  VCENTER_PASSWORD: replace-me
  VCENTER_USERNAME: replace-me
  VCENTER_FINGERPRINT: replace-me
  VM_BASE_PATH: replace-me
  VM_NAME: replace-me
  WINRM_PASSWORD: replace-me
  WINRM_USERNAME: replace-me
  VAGRANT_HOME: replace-me
  VAGRANT_DOTFILE_PATH: replace-me
  VAGRANT_VAGRANTFILE: replace-me
